version: "3.9"

services:
  database:
    container_name: OOPdatabase
    build:
      context: ./database
      dockerfile: Dockerfile
    env_file: ./database/db.env
    volumes:
      - database-data:/var/lib/mysql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5
    # expose:
    #   - 5432
    ports:
      - 5432:5432

  backend:
    container_name: OOPbackend
    build:
      context: ./
      dockerfile: ./backend/Dockerfile
    # env_file: ./backend/.env
    depends_on:
      database:
        condition: service_healthy
    ports: 
      - 8080:8080

  # frontend:
  #   container_name: frontend
  #   build:
  #     context: ./frontend
  #     dockerfile: Dockerfile
  #   depends_on:
  #     - backend

volumes:
  database-data:
