version: '3.9'

services:
  database:
    container_name: database
    build:
      context: ./database
      dockerfile: Dockerfile
    env_file: ./database/.env
    volumes:
      - database-data:/var/lib/mysql
    expose: 
      - 5432

  backend:
    container_name: backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    env_file: ./backend/.env
    depends_on:
      - database
    expose: 
      - 8888

  frontend:
    container_name: frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    depends_on:
      - backend

volumes:
  database-data: